### ISSUE TITLE
Allow Gradients or Dynamic Line Colors

### ISSUE THREAD

**Issue by anagrius** [terezka/line-charts#5]
In order to produce effects like:

<img width="195" alt="screen shot 2017-12-04 at 19 57 19" src="https://user-images.githubusercontent.com/157210/33570570-85c4ce56-d92d-11e7-9353-70a6a04864e8.png">

Here github's project activity charts, we have to have control of the line's/area's color a bit more.

Have you considered making the color (x,y) dependent function:

color : (Float, Float) -> Color

or maybe simply allowing a gradient between max and min of the axis.

**Comment by terezka** [comment]
Sounds reasonable!

**Comment by anagrius** [comment]
Not sure the `(x,y) -> Color` is super useful (at least for me). I was able to get the desired effect by including a `linearGradient` (hard-coded) in defs and setting the stroke of `interpolation__line` to that.

Here is the result, bash in its gloriousness:

<img width="124" alt="screen shot 2017-12-06 at 19 42 20" src="https://user-images.githubusercontent.com/157210/33678960-b0e8c2f4-dabd-11e7-9874-1c16b49fb606.png">

**Comment by terezka** [comment]
My current idea is to set the gradient between min and max, but I haven't tried to implement anything yet since I'm focusing on the date time axes. I'll get back to you if I have any questions when I start working on it. :)

**Comment by anagrius** [comment]
Thats what I would do too.
