### ISSUE TITLE
`elm package install` doesn't exist in elm 0.19.0

### ISSUE THREAD

**Issue by mathicalee** [terezka/line-charts#52]
Hi everyone,

I am very new to elm (2 days) and I see there is a new version of elm, 0.19.0, which is installed on my machine.

Now I wanted to run `elm package install` but the tool says that this command doesn't exist. `elm install` doesn't work either.

What would be the best way to build it and see the examples in elm 0.19.0? I also would like to change the READMEs if I get it work. Thanks in advance!

Best

**Comment by mathicalee** [comment]
The 0.19.0 requires a elm.json file, and all the dependencies should have this file (I guess).

I did `elm init` and tried to install all dependencies with `elm install [package]` and it succeeded only with package `debois/elm-dom` and `myrho/elm-round`. This are the only ones which has a elm.json instead of elm-package.json.

Other packages are not ready yet.

**Comment by joecorkerton** [comment]
This package hasn't been update for 0.19 yet. @terezka are there plans to update this package? I have found it very useful

**Comment by MarcCoquand** [comment]
Would be a shame if this was not updated. Could we create a TODO of what needs to be done? Then maybe I can help out.

**Comment by terezka** [comment]
Yes! I'm waiting one some dependencies being updates / me having the time to remove those dependencies (probably after elm-conf) - whichever comes first!

**Comment by JonRowe** [comment]
Is there anything that could be done to help upgrading to 0.19?

**Comment by terezka** [comment]
Hi! The code is updated, but something is wrong and I can't publish the package. @evancz is looking into it. :)

**Comment by JonRowe** [comment]
Awesome! Thanks! Would love it if you could drop a mention here when this is released as I'm sure theres a few watchers waiting on this! Thanks for your hard work!

**Comment by terezka** [comment]
Sure!

**Comment by terezka** [comment]
Hi @JonRowe! The Elm 0.19 version should be published now. https://package.elm-lang.org/packages/terezka/line-charts/latest/

**Comment by mathicalee** [comment]
Thanks! I'll close this issue :D

**Comment by daveman1010221** [comment]
Hi. I'm also new to elm and am finding this page in January of 2020. Is 'elm package install' still relevant or is there some other way to make this work with an older project? I'm not really sure what the command did, so it's hard to fix it some other way. Thanks.

**Comment by JonRowe** [comment]
It's `elm install [package]`
